-- MySQL Script generated by MySQL Workbench
-- Wed May  1 23:02:43 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema entregable
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema entregable
-- -----------------------------------------------------
DROP DATABASE IF EXISTS entregable;
CREATE SCHEMA IF NOT EXISTS `entregable` DEFAULT CHARACTER SET utf8mb4 ;
USE `entregable` ;

-- -----------------------------------------------------
-- Table `entregable`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregable`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entregable`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregable`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  `apellido` VARCHAR(250) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `contraseña` VARCHAR(25) NOT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_categoria1_idx` (`id_categoria` ASC) ,
  CONSTRAINT `fk_usuarios_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `entregable`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entregable`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregable`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(250) NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  `imagen` BLOB NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_finalizacion` DATE NOT NULL,
  `cupo_maximo` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entregable`.`usuarios_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregable`.`usuarios_cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `cursos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_has_cursos_cursos1_idx` (`cursos_id` ASC) ,
  INDEX `fk_usuarios_has_cursos_usuarios1_idx` (`usuarios_id` ASC) ,
  CONSTRAINT `fk_usuarios_has_cursos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `entregable`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_cursos_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `entregable`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entregable`.`unidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregable`.`unidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(250) NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `cursos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_unidades_cursos1_idx` (`cursos_id` ASC) ,
  CONSTRAINT `fk_unidades_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `entregable`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entregable`.`clases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregable`.`clases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(250) NOT NULL,
  `descripcion` VARCHAR(250) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `marca_visibilidad` TINYINT NOT NULL,
  `unidades_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clases_unidades1_idx` (`unidades_id` ASC) ,
  CONSTRAINT `fk_clases_unidades1`
    FOREIGN KEY (`unidades_id`)
    REFERENCES `entregable`.`unidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entregable`.`bloques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entregable`.`bloques` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(250) NOT NULL,
  `tipo` VARCHAR(250) NOT NULL,
  `contenido` VARCHAR(250) NOT NULL,
  `clases_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bloques_clases1_idx` (`clases_id` ASC) ,
  CONSTRAINT `fk_bloques_clases1`
    FOREIGN KEY (`clases_id`)
    REFERENCES `entregable`.`clases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
